[dolphin]
version = "0.1.0"
owner = "The HyDE Project"
action = "sync"

[[dolphin.dependency]]
yay = ["dolphin"]
paru = ["dolphin"]
dnf = ["dolphin"]

[[dolphin.files]]
source_root = "Configs"
target_root = "${HOME}"
paths = [
    ".config/dolphinrc",
    ".local/share/dolphin",
    ".local/share/kio/servicemenus/hydewallpaper.desktop",
    ".local/share/kxmlgui5/dolphin",
]

[[dolphin.files]]
action = "preserve"
source_root = "Configs/.local/state"
target_root = "${HOME}/.local/state"
paths = "dolphinstaterc"

[applications_menu]
pre_command = "echo 'Sync applications menu'"

[[applications_menu.files]]
action = "sync"
source_root = "Configs/.config/menus"
target_root = "${XDG_CONFIG_HOME}/menus"
paths = "applications.menu"
