
[dunst]
pre_command = "echo 'Pre commands '" # Pre commands
post_command = "echo 'HyDE backed up!'" # Post commands

[[dunst.dependency]]
pacman = ["dunst"]
yay = ["dunst"]
paru = ["dunst"]
dnf = ["dunst"]

[[dunst.files]]
action = "sync"
source_root = "hyde/wallbash.dunst.sh"
target_root = "${XDG_CONFIG_HOME}"
paths = "hyde/wallbash.dunst.sh"
