[electron]
pre_command = "echo 'Preserve electron flags'"

[[electron.dependency]]
yay = ["electron"]

[[electron.files]]
action = "preserve"
source_root = "Configs/.config"
target_root = "${XDG_CONFIG_HOME}"
paths = "electron-flags.conf"
