[kitty]
pre_command = "echo 'Pre commands '" # Pre commands
post_command = "echo 'HyDE backed up!'" # Post commands

[[kitty.dependency]]
yay = ["kitty"] # Dependency for kitty

[[kitty.files]]
action = "sync"
source_root = "Configs/.config/"
target_root = "${XDG_CONFIG_HOME}"
paths = ["kitty/hyde.conf", "kitty/kitty.conf"]

[[kitty.files]]
action = "preserve"
source_root = "Configs/.config/"
target_root = "${XDG_CONFIG_HOME}"
paths = "kitty/theme.conf"

[[kitty.files.dependency]]
yay = ["imagemagick", "hyprland"]
