[hyprsunset]

[[hyprsunset.dependency]]
yay = ["hyprsunset"]
paru = ["hyprsunset"]
dnf = ["hyprsunset"]

[[hyprsunset.files]]
action = "preserve"
source_root = "Configs/.config/hypr"
target_root = "${XDG_CONFIG_HOME}/hypr"
paths = "hyprsunset.conf"
