-- Apply leftover hyprlang files the Lua parser will not source.
-- monitors.conf is still generated by nwg-displays.

local M = {}

local function trim(s)
	return (s:gsub("^%s+", ""):gsub("%s+$", ""))
end

local function split_csv(s)
	local out = {}
	for part in (s .. ","):gmatch("([^,]*),") do
		out[#out + 1] = trim(part)
	end
	return out
end

local function merge_monitor_line(acc, rhs)
	local f = split_csv(rhs)
	local output = f[1]
	if not output then
		return
	end
	acc[output] = acc[output] or { output = output }
	local spec = acc[output]
	if f[2] == "transform" then
		spec.transform = tonumber(f[3]) or f[3]
		return
	end
	if f[2] and f[2]:find("%d") then
		spec.mode = f[2]
		spec.position = f[3]
		spec.scale = tonumber(f[4]) or f[4]
		local i = 5
		while i <= #f do
			local k = f[i]
			local v = f[i + 1]
			if k == "bitdepth" then
				spec.bitdepth = tonumber(v) or v
			elseif k == "transform" then
				spec.transform = tonumber(v) or v
			elseif k == "cm" then
				spec.cm = v
			elseif k == "icc" then
				spec.icc = v
			end
			i = i + 2
		end
	end
end

function M.apply_monitors(path)
	local handle = io.open(path, "r")
	if not handle then
		return
	end
	local acc = {}
	for raw in handle:lines() do
		local line = trim(raw)
		if line ~= "" and not line:find("^#") then
			local rhs = line:match("^monitor%s*=%s*(.*)$")
			if rhs then
				local hash = rhs:find("#", 1, true)
				if hash then
					rhs = trim(rhs:sub(1, hash - 1))
				end
				merge_monitor_line(acc, rhs)
			end
		end
	end
	handle:close()
	for _, spec in pairs(acc) do
		hl.monitor(spec)
	end
end

return M
